import {buildGeometry, compareGeometry} from '../../lib/cad/geometry';
import {sample} from '../../lib/cad/model';
import {createTemplate} from '../../lib/cad/templates';
import {writeFileSync} from 'node:fs';
const after=structuredClone(sample); after.operations[2].position[0]=-17;
const bare=structuredClone(sample); bare.operations=bare.operations.slice(0,2);
const diff=compareGeometry(sample,after);
const movement=Array.from({length:49},(_,i)=>{const m=structuredClone(sample);m.operations[2].position[0]=17-34*i/48;return Array.from(buildGeometry(m).positions)});
const data={before:Array.from(buildGeometry(sample).positions),after:Array.from(buildGeometry(after).positions),shell:Array.from(buildGeometry(bare).positions),bracket:Array.from(buildGeometry(createTemplate('bracket')).positions),enclosure:Array.from(buildGeometry(createTemplate('enclosure')).positions),movement,added:Array.from(diff.added),removed:Array.from(diff.removed),unchanged:Array.from(diff.unchanged)};
writeFileSync('artifacts/video-intro-v2/meshes.json',JSON.stringify(data));
